export const BASE_URL = 'http://localhost:8000'
export const LANDING_PAGE = '/'
export const LOGIN_PAGE = '/login'
export const REGISTER_USER_PAGE = '/register_user'
export const REGISTER_EVENT_LOCATION_PAGE = '/register_location'
export const REGISTER_EVENT_PAGE = '/register_event'
export const LOGOUT_PAGE = '/logout'
export const ALL_EVENTS_PAGE = '/all_events'
